### ISSUE TITLE
STM32F407VGT7 vs STM32F407VGT6

### ISSUE THREAD

**Issue by bpaglier** [rglenn/unocart2600-pcb#1]
Hello,

I have been looking for the microcontroller specified in the design and STM32F407VGT7 are currently on back order everywhere, however STM32F407VGT76 are available. The only thing I can find in the specs that is obviously different is max operating temperature. With the STM32F407VGT7 having a max temp of 105c and the STM32F407VGT6 having a max temp of 85c. I am just getting back into electronics however I would think for this project that difference wouldn't matter? Am I missing something else? Any help you can provide would be much appreciated.  

Thanks in advance,

bpaglier

**Comment by rglenn** [comment]
Hi bpaglier,

The STM32F407VGT6 works fine - it's actually what I used. For the schematic, I just went with the one that was in the Kicad library.
